"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.voodooPost = exports.voodooGet = exports.voodooDelete = exports.singleInstanceLock = exports.setUriScheme = exports.setupIPC = exports.handleWindowsSecondInstance = exports.handleNavigation = exports.handleMacOSSecondInstance = exports.createDevToolsLogger = void 0;
var createDevToolsLogger_1 = require("./createDevToolsLogger");
Object.defineProperty(exports, "createDevToolsLogger", { enumerable: true, get: function () { return createDevToolsLogger_1.createDevToolsLogger; } });
var handleMacOSSecondInstance_1 = require("./handleMacOSSecondInstance");
Object.defineProperty(exports, "handleMacOSSecondInstance", { enumerable: true, get: function () { return handleMacOSSecondInstance_1.handleMacOSSecondInstance; } });
var handleNavigation_1 = require("./handleNavigation");
Object.defineProperty(exports, "handleNavigation", { enumerable: true, get: function () { return handleNavigation_1.handleNavigation; } });
var handleWindowsSecondInstance_1 = require("./handleWindowsSecondInstance");
Object.defineProperty(exports, "handleWindowsSecondInstance", { enumerable: true, get: function () { return handleWindowsSecondInstance_1.handleWindowsSecondInstance; } });
var setupIPC_1 = require("./setupIPC");
Object.defineProperty(exports, "setupIPC", { enumerable: true, get: function () { return setupIPC_1.setupIPC; } });
var setUriScheme_1 = require("./setUriScheme");
Object.defineProperty(exports, "setUriScheme", { enumerable: true, get: function () { return setUriScheme_1.setUriScheme; } });
var singleInstanceLock_1 = require("./singleInstanceLock");
Object.defineProperty(exports, "singleInstanceLock", { enumerable: true, get: function () { return singleInstanceLock_1.singleInstanceLock; } });
var voodooDelete_1 = require("./voodooDelete");
Object.defineProperty(exports, "voodooDelete", { enumerable: true, get: function () { return voodooDelete_1.voodooDelete; } });
var voodooGet_1 = require("./voodooGet");
Object.defineProperty(exports, "voodooGet", { enumerable: true, get: function () { return voodooGet_1.voodooGet; } });
var voodooPost_1 = require("./voodooPost");
Object.defineProperty(exports, "voodooPost", { enumerable: true, get: function () { return voodooPost_1.voodooPost; } });
